### ISSUE TITLE
Dolby atmos for gaming wont run but dolby atmos will

### ISSUE THREAD

**Issue by Xii-Nyth** [AlanFinotty/AAFOptimusDCHAudio-Generic#1]
Im guessing if I run the installer a second time now that the driver is installed I can install atmos for gaming and it will work, but the installer doesnt let me

**Comment by AlanFinotty** [comment]
There may still be some residue on your system.

**Comment by Xii-Nyth** [comment]
When I try unistalling it normally with the unistaller or from device manager, I have to restart to fully remove it, and in doing so windows immediately installs an old realtek driver, braking all the software. 

is there a way I could unistall the driver itself (or any packages needed), without effecting the other software, while still in windows, so I can run the installer again withoutu restarting?

**Comment by AlanFinotty** [comment]
There is this tool from Microsoft itself that serves to hide updates, including driver updates.

[wushowhide.zip](https://github.com/AlanFinotty/AAFOptimusDCHAudio-Generic/files/9209982/wushowhide.zip)

**Comment by Xii-Nyth** [comment]
Yeah that doesnt work, neither does turning them off in gepedit, next step would be to try blocking conenction to windows update.

These issues are mostly exclusive to laptops from my experiance (and prebuilts?) will try on my pc.

Anyways this is just windows related so Ill close the issue.
