### ISSUE TITLE
RPC service connection problem of Realtek Audio console app

### ISSUE THREAD

**Issue by Pocarai** [AlanFinotty/AAFOptimusDCHAudio-Generic#12]
I install the latest update of the AAF Audio Driver and after all. This was happened. unlike in previous update
![image](https://user-images.githubusercontent.com/96225118/202852080-ff5e664b-d026-4ff4-be05-9163125f9f1a.png)

**Comment by OneOfMany07** [comment]
(random passerby considering trying these out)  Is there a service that fails to start?  I'd look through the services.msc list and/or the event viewer to see if a specific failure can be looked into.  Those cryptic hardware errors can be very helpful.

**Comment by AlanFinotty** [comment]
This package is based on the generic Microsoft HdAudio driver, therefore it will not be able to run Realtek Audio Console.
