### ISSUE TITLE
RTX 3090 no audio

### ISSUE THREAD

**Issue by PrMinisterGR** [AlanFinotty/AAFOptimusDCHAudio-Generic#13]
Hello,

The Windows installation is as follows:
Windows 11, 22H2, Build Number 2262.819

I installed just the Bus driver and the Dolby Digital component (the top two components on the installer), on a clean system, after installing my GPU driver.

When installing the NVIDIA GPU driver, I did not select the audio driver.

The issue I have with my GPU is that I never get audio with any driver (even Microsoft provided), except the NVIDIA driver. Your driver installs, all the options are there, but there is no sound. This is no matter the output format. There is no error anywhere, and I can see the bars "playing" when the audio plays but there is no sound.

Is there any idea on how to change or check this? This happens on a clean installation, and on a "dirty" one, it is always exactly the same behavior, and it also happens with the Microsoft generic driver, not just yours.

The only feature I really want is the Dolby Digital + encoding, nothing else.

Thank you for your work!

**Comment by apanovski** [comment]
I'm experiencing the same issue with my RTX 3080. In my situation, Dolby Digital encoding over HDMI works when I initially install the driver, but I'm getting no audio as soon as I switch to a different monitor and revert back to my LG CX.

**Comment by AlanFinotty** [comment]
Most recent version with NVIDIA HDMI Audio Driver

**Comment by PrMinisterGR** [comment]
Does this mean it is fixed in the latest version?
