### ISSUE TITLE
[QUESTION] Does this work with bluetooth audio/usb audio?

### ISSUE THREAD

**Issue by Shituation** [AlanFinotty/AAFOptimusDCHAudio-Generic#17]
I installed the package but it only worked for my hdmi audio, I'm currently using two devices (each at a time): a bluetooth headphone and an emotiva audio usb external card.

This is me installing the drivers:
![image_proxy](https://user-images.githubusercontent.com/43975882/216735063-bc8a5d45-2fb0-478c-b207-0564d30b9d36.jpg)

I installed blindly picking options, the forum is too chaotic to be used as guide.

**Comment by AlanFinotty** [comment]
It doesn't support bluetooth audio yet, but I'm working on it.
