### ISSUE TITLE
Would this work on a chromebook that has windows 10 installed?

### ISSUE THREAD

**Issue by Usulyre** [AlanFinotty/AAFOptimusDCHAudio-Generic#19]
Hi, if i tried to install this on a chromebook with windows 10 installed, would it enable sound if i could not get sound working by default?

Samsung Chromebook 4

Let me know if you need any technical info

**Comment by AlanFinotty** [comment]
This package is designed to work with all devices that use the HDAUDIO enumerator. If your equipment has an audio chip that fits this requirement, it will work.
