### ISSUE TITLE
Creative Sound BlasterX AE-5 Plus

### ISSUE THREAD

**Issue by BlankFX1** [AlanFinotty/AAFOptimusDCHAudio-Generic#3]
Any Chance to support Creative Sound Blaster X AE-5 Plus?

Hardware IDs:
Sound BlasterX AE-5 Plus
HDAUDIO\FUNC_01&VEN_1102&DEV_0011&SUBSYS_11020191&REV_1009
HDAUDIO\FUNC_01&VEN_1102&DEV_0011&SUBSYS_11020191

Sound Blaster Audio Controller
PCI\VEN_1102&DEV_0012&SUBSYS_01911102&REV_01
PCI\VEN_1102&DEV_0012&SUBSYS_01911102
PCI\VEN_1102&DEV_0012&CC_040300
PCI\VEN_1102&DEV_0012&CC_0403

I also tried to use the Realtek-Version for my onboard Realtek-Sound, but ran into a similar issue: This Device Cannot Start (Code 10)
Not really using this sound chip, but maybe it can help:
HDAUDIO\FUNC_01&VEN_10EC&DEV_0B00&SUBSYS_10438797&REV_1000
HDAUDIO\FUNC_01&VEN_10EC&DEV_0B00&SUBSYS_10438797

**Comment by AlanFinotty** [comment]
This support is already enabled. But, remembering that, there are some peculiar audio chips not supported by the generic driver. I had an AsRock N68C-S UCC motherboard with a VIA VT1705 audio chip. I tried using the generic driver with the same and it didn't work for nothing.
