### ISSUE TITLE
DTS Not licensed

### ISSUE THREAD

**Issue by aaartech** [AlanFinotty/AAFOptimusDCHAudio-Generic#5]
DTS Sound Unbound only gives option to buy or try free trial on new update

**Comment by AlanFinotty** [comment]
The DTS Sound Unbound application contained in this package must not be updated via the Microsoft Store, otherwise you will lose the license for DTS Spatial Sound.

**Comment by aaartech** [comment]
I was using Realtek, that's why I thought I should install the Realtek version and DTS was having problems, but now I'm using the generic version and the problem is solved.
